version: '3'

services:

  influx:
    image: influxdb:1.4
    volumes:
      - ./container-data/database:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana: # uncomment this if u need raw data access
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./container-data/grafana:/var/lib/grafana
    depends_on:
      - "influx"

  data-provider: # node server that gets data from influxdb and sends to browser
    build: ./server
    ports:
      - 8080:8080
    depends_on:
      - "influx"

  visualization: # apache server that servers visualization webapp to client
                 # Note: this container takes a long time to build, so if you
                 # don't have time for that, run `npm run dev` instead in the
                 # `visualization` directory AFTER running `docker-compose up`.
    build: ./visualization
    depends_on:
      - "data-provider"
    ports:
      - 80:80