version: '3'

services:

  influx:
    image: influxdb:1.4
    volumes:
      - ./container-data/database:/var/lib/influxdb
    ports:
      - 8086:8086

  # receiver:
  #   build: ./rfInterface/
  #   #devices:
  #   #  - "/dev/ttyUSB1:/USB"
  #   depends_on:
  #     - "influx"
  #   ports:
  #     - 5000:5000

  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./container-data/grafana:/var/lib/grafana
  #   depends_on:
  #     - "influx"

  #apache:
  #  image: httpd:2.4
  #  environment:
  #    - VIRTUAL_HOST=visualization.codelis.local
  #  volumes:
  #    - ./visualization:/usr/local/apache2/htdocs/

  data-provider:
    build: ./server
    ports:
      - 8080:8080

  # visualization:
  #   build: ./visualization
  #   depends_on:
  #     - "data-provider"
  #   ports:
  #     - 8081:80