version: '3'

services:

  influx:
    image: influxdb:1.4
    volumes:
      - ./container-data/database:/var/lib/influxdb
    ports:
      - 8086:8086

  receiver: # python script communicating with xbee
    build: ./rfInterface/
    #devices:
    #  - "/dev/ttyUSB1:/USB"
    depends_on:
      - "influx"
    ports:
      - 5000:5000

  # grafana: # if u need raw data access
  #   image: grafana/grafana
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./container-data/grafana:/var/lib/grafana
  #   depends_on:
  #     - "influx"

  data-provider: # node server that gets data from influxdb and sends to browser
    build: ./server
    ports:
      - 8080:8080

  # visualization: # apache server that servers visualization webapp to client
  #   build: ./visualization
  #   depends_on:
  #     - "data-provider"
  #   ports:
  #     - 8081:80