version: '3'

services:

  influx:
    image: influxdb:1.4
    volumes:
      - ./container-data/database:/var/lib/influxdb

  receiver:
    build: ./rfInterface/
    #devices:
    #  - "/dev/ttyUSB1:/USB"
    depends_on:
      - "influx"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./container-data/grafana:/var/lib/grafana
    depends_on:
      - "influx"
