version: '3'

services:

  influx:
    image: influxdb:1.4
    volumes:
      - ./container-data/database:/var/lib/influxdb
      - ./mestral_data/influx_backups:/backups
    # ports:
    #   - 8086:8086

  data-provider: # node server that gets data from influxdb and sends to browser
    build: ./server
    # ports:
    #   - 8080:8080
    depends_on:
      - "influx"

  visualization:
    build: ./visualization
    depends_on:
      - "data-provider"
    # ports:
    #   - 80:80

networks:
  default:
    name: fsn-internal-network
    external: true
